In [190]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [191]:
cp = pd.read_csv('CarPrice.csv')
cp.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [192]:
#Data Preprocessing
cp.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    str
 3   fueltype          205 non-null    str
 4   aspiration        205 non-null    str
 5   doornumber        205 non-null    str
 6   carbody           205 non-null    str
 7   drivewheel        205 non-null    str
 8   enginelocation    205 non-null    str
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    str
 15  cylindernumber    205 non-null    str
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    str
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), str(10)
memory usage: 41.8 KB

In [193]:
#check for NA values
cp.isnull().sum()

#no missing values

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [194]:
cp.drop('car_ID', axis = 1, inplace= True)

In [195]:
cp.head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [196]:
#exploring each feature
cp['fuelsystem'].value_counts()

#getting list of columns that are not int or float excluding price

Str_cols = [features for features in cp.columns if cp[features].dtypes=='str']

print(Str_cols)

Str_cols.remove('CarName')

['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber', 'fuelsystem']

In [197]:
#encoding all features

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop = 'first', sparse_output= False)
encoded_array = encoder.fit_transform(cp[Str_cols])

encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(Str_cols))



encoded_df.head()

,fueltype_gas,aspiration_turbo,doornumber_two,carbody_hardtop,carbody_hatchback,carbody_sedan,carbody_wagon,drivewheel_fwd,drivewheel_rwd,enginelocation_rear,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [198]:
#dropping categorical features
cp.drop(Str_cols, axis = 1, inplace= True)

In [199]:
#drop car name as well
cp.drop('CarName', axis = 1, inplace= True)

In [200]:
#concate both int data and encoded data
cp = pd.concat([cp, encoded_df], axis= 1)
cp.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   symboling              205 non-null    int64
 1   wheelbase              205 non-null    float64
 2   carlength              205 non-null    float64
 3   carwidth               205 non-null    float64
 4   carheight              205 non-null    float64
 5   curbweight             205 non-null    int64
 6   enginesize             205 non-null    int64
 7   boreratio              205 non-null    float64
 8   stroke                 205 non-null    float64
 9   compressionratio       205 non-null    float64
 10  horsepower             205 non-null    int64
 11  peakrpm                205 non-null    int64
 12  citympg                205 non-null    int64
 13  highwaympg             205 non-null    int64
 14  price                  205 non-null    float64
 15  fueltype_gas           205 non-null    float64
 16  aspiration_turbo       205 non-null    float64
 17  doornumber_two         205 non-null    float64
 18  carbody_hardtop        205 non-null    float64
 19  carbody_hatchback      205 non-null    float64
 20  carbody_sedan          205 non-null    float64
 21  carbody_wagon          205 non-null    float64
 22  drivewheel_fwd         205 non-null    float64
 23  drivewheel_rwd         205 non-null    float64
 24  enginelocation_rear    205 non-null    float64
 25  enginetype_dohcv       205 non-null    float64
 26  enginetype_l           205 non-null    float64
 27  enginetype_ohc         205 non-null    float64
 28  enginetype_ohcf        205 non-null    float64
 29  enginetype_ohcv        205 non-null    float64
 30  enginetype_rotor       205 non-null    float64
 31  cylindernumber_five    205 non-null    float64
 32  cylindernumber_four    205 non-null    float64
 33  cylindernumber_six     205 non-null    float64
 34  cylindernumber_three   205 non-null    float64
 35  cylindernumber_twelve  205 non-null    float64
 36  cylindernumber_two     205 non-null    float64
 37  fuelsystem_2bbl        205 non-null    float64
 38  fuelsystem_4bbl        205 non-null    float64
 39  fuelsystem_idi         205 non-null    float64
 40  fuelsystem_mfi         205 non-null    float64
 41  fuelsystem_mpfi        205 non-null    float64
 42  fuelsystem_spdi        205 non-null    float64
 43  fuelsystem_spfi        205 non-null    float64
dtypes: float64(37), int64(7)
memory usage: 70.6 KB

In [ ]:
#checking for outliers in int values
cp.columns.dtype(int)

In [ ]:
#cp.to_csv('car_price_cleaned.csv')